version: '3.8'
services:
  chat:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3000:3000'